### ISSUE TITLE
This lib is "production ready" ?

### ISSUE THREAD

**Issue by euclid1990** [kataras/neffos#2]
I want to integrate websocket to my project, and I have a plan using nodejs/socket.io. and after looked at the neffos project carefully, I consider using this library.
But does it ready for production now ?
Thank you for contribute many wonderful projects !

**Comment by kataras** [comment]
Hello @euclid1990, if you are/was using [iris](https://github.com/kataras/iris) you better wait some days because it will be adopted by the web framework itself. Otherwise yes you can use it but I am responsible enough to not tell you that it is a production-ready project so soon. It is a new project, I think I finish it, I tested it for the past months but  I am here for any issues that may come, support is the 99% of a software success. Feel free to use it. It has probably less struggles then socket.io, that's for sure.

And thank you a lot for your compliment, I am very grateful!

**Comment by euclid1990** [comment]
@kataras Thank you for reply. I will wait when it adopted into iris.
