### ISSUE TITLE
[BUG] the process hang up, CPU become 100% 

### ISSUE THREAD

**Issue by LeeEirc** [kataras/neffos#32]
**Describe the bug**

I use neffos as WebSocket server to  handler all WebSocket connects from browser.
It is running well when first deploy the web Application on production server. However it became weird at some moment. The CPU became 100% usage, and the server could not handle any incoming WebSocket connection. Debugging by dlv tool, I found the neffos conn's goroutine block main process.  I don't know how reproduce this bug, but it happened several times on productions environment.  

**To Reproduce**

**Expected behavior**
I hope how to avoid this situation or this is the bug. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32626707/75847636-b52ce380-5e1a-11ea-8070-cbbd69ca0cad.png)

![image](https://user-images.githubusercontent.com/32626707/75847671-ce359480-5e1a-11ea-94bc-03be271c7609.png)

**Desktop (please complete the following information):**
 - OS:  Centos
 - Version  7

**Comment by kataras** [comment]
@LeeEirc you use an older version, could you please upgrade to `v0.0.14` and verify if you still having issues.

**Comment by LeeEirc** [comment]
@kataras Thank you for rely. I will upgrade to v0.0.14. However I am not sure it could fix this issue. Could you give some clues to find the root cause? Why does it block main process even thought the code running on the separate goroutine.

**Comment by kataras** [comment]
The broadcaster was not correctly implemented for huge amount of messages circles. The broadcaster has been refactored and it plays pretty fast, it's a "hack" in order to reduce loops and sync lockers as much as possible and it's ignored when redis or nats publish/subscribe mechanism is involved(which is highly recommended when your application has to serve millions of requests https://github.com/kataras/neffos/wiki/Scale-out).
